<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'UniversityOfAppliedScienceUpperAustria\\Kwm2020\\' => array($typo3InstallDir . 'typo3conf/ext/kwm2020/Classes'),
);
